ALTER TABLE users ADD COLUMN full_name VARCHAR(150);
ALTER TABLE users ADD COLUMN email VARCHAR(150);
ALTER TABLE users ADD COLUMN phone VARCHAR(30);
ALTER TABLE users ADD COLUMN matricule VARCHAR(30);
ALTER TABLE users ADD COLUMN profile_photo TEXT;
